### ISSUE TITLE
Tests plus poussés des invariants

### ISSUE THREAD

**Issue by n-peugnet** [Atlaoui/ParallelProgramingInterface#22]
Invariants des algos pour chaque test.

Et pour peersim seulement

Invariants d'ordre des evenements

**Comment by max0218** [comment]
Invariants des algos pour chaque test c'est à dire que pour chaque test on choisit des invariants et on vérifie qu'ils sont respectés pour plusieurs seed ? Genre le dernier message d'un algo de Ring revient bien vers le node 0 ou des choses comme ça ?

**Comment by n-peugnet** [comment]
Exactement

**Comment by max0218** [comment]
Bon j'ai créé une branche pour essayer ça, j'ai testé en indiquant simulation.experiments à 2 dans le fichier de config de peersim pour ne pas avoir l'exception de double instanciation de la configuration.
Et donc la deuxième simulation se lance mais n'éxécute rien..

**Comment by n-peugnet** [comment]
bon du coup ça c'est fait
