### ISSUE TITLE
Lancer plusieurs fois Peersim dans les tests

### ISSUE THREAD

**Issue by n-peugnet** [Atlaoui/ParallelProgramingInterface#23]

**Comment by max0218** [comment]
En fait c'est plutôt ici que j'aurais du parler.
Alors j'ai réussi à faire tourner le second experiment mais ça génère une nouvelle random seed pour le 2e du coup ça ne sert à rien si on arrive pas à le refaire tourner avec la même seed.

**Comment by max0218** [comment]
Et en fait le problème principal c'était que nos NodeID ne correspondaient plus au Network.getNode pcq les notres étaient 0,1,2,3,4  puis 5,6,7,8,9 alors que le Network réutilise toujours les Node 0,1,2,3,4 à chaque itération de l'algo
