### ISSUE TITLE
infra.wait() et infra.notifayAll()

### ISSUE THREAD

**Issue by n-peugnet** [Atlaoui/ParallelProgramingInterface#24]
Probablement d'abord déplacer le code qui lance un nouveau thread depuis `NodeProcess.handleMessage()` vers `Infrastructure` en ajoutant une fonction intermédiaire.

**Comment by max0218** [comment]
Pourquoi vous vouliez pas garder le message handler et le multithreading dans NodeProcess et y ajouter le wait et notifayAll ?

**Comment by n-peugnet** [comment]
hmm parce que je trouvais ça plus clair pour l'api qu'on est en train de crée que tous les appels se fasse à infra. Mais c'est vrai que c'est pas forcément plus logique de faire `infra.wait()` que `this.wait()`. étant donnée que c'est justement le process qui wait et non l'infra.

Bon je suis partagé. On peut peut-être le laisser comme ça oui
