### ISSUE TITLE
Schéma un peu plus user friendly pour le scénario

### ISSUE THREAD

**Issue by n-peugnet** [Atlaoui/ParallelProgramingInterface#31]
Lorsque j'ai voulu utiliser le scénario j'ai trouvé le scénario par très agréable à écrire.

## Avant : une liste d'objets devant commencer par `Call`
```json
{
	"Call_1": {
		"args": [],
		"FunctionName": "doSomething",
		"Node": 1,
		"Delay": 1
	},
	"Call_2": {
		"args": [],
		"FunctionName": "doSomething",
		"Node": 2,
		"Delay": 1
	}
}
```

## Proposition : un tableau d'evenements

à côté duquel on pourrait par exemple ajouter un tableau de failures

```json
{
	"events": [
		{
			"args": [],
			"FunctionName": "doSomething",
			"Node": 1,
			"Delay": 1
		},
		{
			"args": [],
			"FunctionName": "doSomething",
			"Node": 2,
			"Delay": 1
		}
	],
	"failures": [
		{
			"Node": 1
		}
	]
}
```

WDYT @Atlaoui ?

**Comment by n-peugnet** [comment]
Je ne sais pas encore comment les failures sont définies et quels sont les paramètres mais je serais intéressé par ton avis.

**Comment by Atlaoui** [comment]
j'ai déja changer sur pannes  tu met juste "calls","on" ou "off"  apres tu mets les appel dans une json array (dsl pour la réponse tardive j'avais pas vue) ,aussi je sais pas si tu a vue mais t pas obliger d'ecrire a la main je propose quelque fonctions pour le format apres faut juste les mettre au bon endroit

**Comment by n-peugnet** [comment]
okay cool. Perso j'aime bien pouvoir lire le fichier json tranquillement
