### ISSUE TITLE
Rapport : Chapitre 1 

### ISSUE THREAD

**Issue by max0218** [Atlaoui/ParallelProgramingInterface#52]
Refaire les deux exemples de l'anneau identiques pour MPI et Peersim, et ensuite l'exemple de l'anneau en générique, expliquer chacun des exemples, faut un peu retoucher le début qui mène à ces exemples aussi je crois

**Comment by Atlaoui** [comment]
pour l'introduction j'avais fait une impeux plus longue dans le carnet de bord , si ça peux t'aider 

https://github.com/Atlaoui/ParallelProgramingInterface/blob/master/Rapport_carnet/SAR_ELIET-LY-ATLAOUI-PEUGNET_carnet-de-bord.tex
